# Generated by Django 2.2.1 on 2022-06-22 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devtool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('kind', models.CharField(default='', max_length=30, verbose_name='종류')),
                ('content', models.TextField(default='', max_length=125, verbose_name='개발툴 설명')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='아이디어명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('content', models.TextField(max_length=150, verbose_name='아이디어 설명')),
                ('interest', models.IntegerField(default=0, verbose_name='아이디어 관심도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('devtool', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.Devtool', verbose_name='예상 개발툴')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_star', to='ideas.Idea')),
            ],
        ),
    ]
