spring:
  # DB 연결
  datasource:


  url: jdbc:mysql://localhost:3306/caken?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  username: root
  password: biukzozn1926    # 내 비밀번호로 해야하는 건가?
  driver-class-name: com.mysql.cj.jdbc.Driver

#    # 설치된 H2 DB와 연결 url
#    url: jdbc:h2:tcp://localhost/~/cakeN;MODE=MySQL;DATABASE_TO_LOWER=TRUE
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver  # 접속을 위한 드라이버



  jpa:
    hibernate:
      ddl-auto: create   # 객체를 보고 자동으로 테이블을 생성하도록 설정
    properties:
      hibernate:
        show_sql: true   # Hibernate가 실행한 모든 SQL문 콘솔로 출력
        format_sql: true   # SQL문을 가독성 있게 표현
        globally_quoted_identifiers: true
        use_sql_comments: true   # 디버깅 정보 출력

  h2:
    console:
      enabled: true

#logging:
#  level:
#    org.hibernate.SQL: debug

logging:
  level:
    org.hibernate.type: trace
#    root: debug

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql