spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 158232764987-1uqo4unkhiht00ehp96d8jv3e50rlvt7.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email

          naver:
            # registration
            client-id: V5xE28KtPAdGrT1DGT8w
            client-secret: 5qz7bVkdL6
            redirectUri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization_grant_type: authorization_code
            scope: name, email, profile_image
            client-name: Naver


        provider:
          naver:
            # provider
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response