spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 158232764987-1uqo4unkhiht00ehp96d8jv3e50rlvt7.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
            callback-url: http://localhost:8080/login/oauth2/code/google

          naver:
            # registration
            client-id: V5xE28KtPAdGrT1DGT8w
            client-secret: 5qz7bVkdL6
            redirectUri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization_grant_type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: 7eb33a787b59a1889daa927560478e8d
            client-secret: 3oJ9Ny9QXqBT9NYEaUPSP1dPeqnC8enY
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: kakao
            client-authentication-method: POST


        provider:
          naver:
            # provider
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id